import { Brand, Campaign, ContentPiece, ContentTemplate, PlatformAccount, ScheduleEntry } from "@/types";

export const mockBrands: Brand[] = [
  {
    id: "b1",
    game_name: "Dragon Quest Legends",
    app_store_url: "https://apps.apple.com/app/dragon-quest-legends",
    play_store_url: "https://play.google.com/store/apps/details?id=com.studio.dql",
    tone_of_voice: "Epic, adventurous, exciting - speaks to hardcore gamers",
    target_audience: "Males 18-35, RPG enthusiasts, competitive gamers",
    brand_guidelines: {
      colors: ["#FF6B35", "#1A1A2E", "#E94560"],
      prohibited_words: ["free", "cheap", "boring"],
      style_do: ["Use action verbs", "Reference game lore", "Create urgency"],
    },
    hashtags: ["#DragonQuestLegends", "#MobileGaming", "#RPG", "#EpicBattle"],
    sample_posts: [
      "The Dragon King awaits your challenge. Will you rise to become a legend? Download now!",
      "New update: 50+ legendary weapons, 3 new raid bosses. Your adventure continues!",
    ],
    system_prompt_override: null,
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-20T14:30:00Z",
  },
  {
    id: "b2",
    game_name: "Puzzle Paradise",
    app_store_url: "https://apps.apple.com/app/puzzle-paradise",
    play_store_url: "https://play.google.com/store/apps/details?id=com.studio.pp",
    tone_of_voice: "Fun, casual, friendly - appeals to casual gamers",
    target_audience: "All ages, casual puzzle lovers, commuters looking for quick fun",
    brand_guidelines: {
      colors: ["#FFD93D", "#6BCB77", "#4D96FF"],
      prohibited_words: ["difficult", "hardcore"],
      style_do: ["Use emojis", "Keep it light", "Highlight relaxation"],
    },
    hashtags: ["#PuzzleParadise", "#BrainTeaser", "#CasualGaming"],
    sample_posts: [
      "Need a brain break? 500+ colorful puzzles are waiting for you in Paradise!",
    ],
    system_prompt_override: null,
    created_at: "2026-03-18T08:00:00Z",
    updated_at: "2026-03-25T11:00:00Z",
  },
];

export const mockPlatformAccounts: PlatformAccount[] = [
  {
    id: "pa1",
    platform: "facebook",
    account_name: "Dragon Quest Legends Official",
    platform_user_id: "123456789",
    brand_id: "b1",
    is_active: true,
    token_expires_at: "2026-05-01T00:00:00Z",
    meta: null,
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "pa2",
    platform: "instagram",
    account_name: "@dragonquestlegends",
    platform_user_id: "987654321",
    brand_id: "b1",
    is_active: true,
    token_expires_at: "2026-05-01T00:00:00Z",
    meta: null,
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "pa3",
    platform: "tiktok",
    account_name: "@dql_official",
    platform_user_id: "tiktok_001",
    brand_id: "b1",
    is_active: true,
    token_expires_at: "2026-06-01T00:00:00Z",
    meta: null,
    created_at: "2026-03-16T09:00:00Z",
  },
  {
    id: "pa4",
    platform: "threads",
    account_name: "@dragonquestlegends",
    platform_user_id: "threads_001",
    brand_id: "b1",
    is_active: true,
    token_expires_at: null,
    meta: null,
    created_at: "2026-03-16T09:00:00Z",
  },
  {
    id: "pa5",
    platform: "facebook",
    account_name: "Puzzle Paradise",
    platform_user_id: "fb_pp_001",
    brand_id: "b2",
    is_active: true,
    token_expires_at: "2026-04-20T00:00:00Z",
    meta: null,
    created_at: "2026-03-18T08:00:00Z",
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "c1",
    brand_id: "b1",
    name: "Season 5 Launch",
    description: "Promote the new Season 5 update with raid bosses and legendary weapons",
    status: "active",
    target_platforms: ["facebook", "instagram", "tiktok", "threads"],
    content_types: ["social_post", "video_script", "image_ad"],
    start_date: "2026-04-01",
    end_date: "2026-04-30",
    posting_frequency: { facebook: 2, instagram: 3, tiktok: 1, threads: 2 },
    ab_test_enabled: true,
    variations_per_piece: 2,
    created_by: "user1",
    created_at: "2026-03-28T10:00:00Z",
  },
  {
    id: "c2",
    brand_id: "b1",
    name: "Easter Event",
    description: "Special Easter in-game event promotion",
    status: "draft",
    target_platforms: ["facebook", "instagram"],
    content_types: ["social_post", "image_ad"],
    start_date: "2026-04-15",
    end_date: "2026-04-22",
    posting_frequency: { facebook: 1, instagram: 2 },
    ab_test_enabled: false,
    variations_per_piece: 1,
    created_by: "user1",
    created_at: "2026-03-30T14:00:00Z",
  },
  {
    id: "c3",
    brand_id: "b2",
    name: "Spring Collection",
    description: "New spring-themed puzzle packs",
    status: "active",
    target_platforms: ["facebook", "instagram", "threads"],
    content_types: ["social_post", "caption"],
    start_date: "2026-04-01",
    end_date: "2026-04-15",
    posting_frequency: { facebook: 1, instagram: 2, threads: 1 },
    ab_test_enabled: false,
    variations_per_piece: 1,
    created_by: "user2",
    created_at: "2026-03-29T09:00:00Z",
  },
];

export const mockContent: ContentPiece[] = [
  {
    id: "ct1",
    campaign_id: "c1",
    content_type: "social_post",
    platform: "facebook",
    status: "pending_review",
    body_text:
      "Season 5 has arrived! Face the Void Dragon in the most epic raid battle yet. Gather your guild, forge legendary weapons, and claim your glory. Are you ready, warrior?",
    hashtags: ["#DragonQuestLegends", "#Season5", "#VoidDragon", "#MobileRPG", "#EpicRaid"],
    script_json: null,
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: "vg1",
    variant_label: "A",
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-01T08:00:00Z",
  },
  {
    id: "ct2",
    campaign_id: "c1",
    content_type: "social_post",
    platform: "facebook",
    status: "pending_review",
    body_text:
      "The Void Dragon has awakened. Season 5 brings 50+ new weapons, 3 devastating raid bosses, and an all-new PvP arena. Download the update and prove your worth!",
    hashtags: ["#DragonQuestLegends", "#Season5", "#NewUpdate", "#GamingCommunity"],
    script_json: null,
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: "vg1",
    variant_label: "B",
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-01T08:00:00Z",
  },
  {
    id: "ct3",
    campaign_id: "c1",
    content_type: "social_post",
    platform: "instagram",
    status: "approved",
    body_text:
      "Your legend begins now. Season 5 is LIVE with the most powerful gear, deadliest bosses, and fiercest competition. Link in bio to download!",
    hashtags: ["#DragonQuestLegends", "#Season5", "#MobileGaming", "#RPGLife", "#GamersUnite"],
    script_json: null,
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: null,
    variant_label: null,
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-04-01T08:30:00Z",
    updated_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "ct4",
    campaign_id: "c1",
    content_type: "video_script",
    platform: "tiktok",
    status: "pending_review",
    body_text: "Season 5 Cinematic Trailer Script",
    hashtags: ["#DragonQuestLegends", "#Season5", "#GameTrailer"],
    script_json: {
      title: "Rise of the Void Dragon",
      duration_seconds: 30,
      scenes: [
        {
          scene_number: 1,
          duration_seconds: 3,
          visual_description: "Dark clouds swirl. Camera zooms into a glowing portal.",
          text_overlay: "A NEW THREAT AWAKENS",
          voiceover: null,
          audio_note: "Dramatic orchestral hit",
        },
        {
          scene_number: 2,
          duration_seconds: 8,
          visual_description: "Montage of warriors battling through dungeons with epic weapons.",
          text_overlay: "50+ LEGENDARY WEAPONS",
          voiceover: "Forge your destiny with weapons of unimaginable power.",
          audio_note: "Building epic music",
        },
        {
          scene_number: 3,
          duration_seconds: 10,
          visual_description: "Raid boss battle - Void Dragon breathing dark fire, guild fighting together.",
          text_overlay: "FACE THE VOID DRAGON",
          voiceover: "Unite your guild. Challenge the Void Dragon. Become a legend.",
          audio_note: "Music crescendo",
        },
        {
          scene_number: 4,
          duration_seconds: 5,
          visual_description: "PvP arena showcase with fast cuts of combat moves.",
          text_overlay: "ALL-NEW PVP ARENA",
          voiceover: null,
          audio_note: "Fast-paced electronic beat",
        },
        {
          scene_number: 5,
          duration_seconds: 4,
          visual_description: "Game logo with download buttons (App Store + Google Play).",
          text_overlay: "DOWNLOAD FREE NOW",
          voiceover: "Dragon Quest Legends Season 5. Download free now.",
          audio_note: "Logo sting",
        },
      ],
      cta: "Download Free Now",
      music_suggestion: "Epic orchestral with electronic elements, building to climax",
    },
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: null,
    variant_label: null,
    llm_model: "claude-opus-4-6",
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-04-01T09:00:00Z",
  },
  {
    id: "ct5",
    campaign_id: "c1",
    content_type: "image_ad",
    platform: "facebook",
    status: "pending_review",
    body_text: "Forge Your Legend",
    hashtags: null,
    script_json: null,
    template_id: "banner_1200x628",
    rendered_image_url: null,
    media_urls: null,
    variant_group: null,
    variant_label: null,
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-04-01T09:30:00Z",
    updated_at: "2026-04-01T09:30:00Z",
  },
  {
    id: "ct6",
    campaign_id: "c1",
    content_type: "social_post",
    platform: "threads",
    status: "scheduled",
    body_text:
      "Season 5 just dropped and the Void Dragon is NO JOKE. Who's already attempted the raid? Drop your best loot finds below!",
    hashtags: ["#DragonQuestLegends", "#Season5"],
    script_json: null,
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: null,
    variant_label: null,
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-04-02T08:00:00Z",
  },
  {
    id: "ct7",
    campaign_id: "c1",
    content_type: "social_post",
    platform: "instagram",
    status: "published",
    body_text:
      "The wait is over. Season 5: Rise of the Void Dragon is HERE. New weapons. New raids. New glory. Link in bio!",
    hashtags: ["#DragonQuestLegends", "#Season5", "#RPG", "#MobileGaming"],
    script_json: null,
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: null,
    variant_label: null,
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-03-31T12:00:00Z",
    updated_at: "2026-04-01T11:00:00Z",
  },
  {
    id: "ct8",
    campaign_id: "c3",
    content_type: "social_post",
    platform: "facebook",
    status: "rejected",
    body_text: "Spring is here! Try our new puzzles!",
    hashtags: ["#PuzzleParadise"],
    script_json: null,
    template_id: null,
    rendered_image_url: null,
    media_urls: null,
    variant_group: null,
    variant_label: null,
    llm_model: "claude-sonnet-4-5-20250514",
    created_at: "2026-04-01T07:00:00Z",
    updated_at: "2026-04-01T09:00:00Z",
  },
];

export const mockSchedule: ScheduleEntry[] = [
  {
    id: "s1",
    content_id: "ct6",
    platform_account_id: "pa4",
    scheduled_at: "2026-04-03T09:00:00Z",
    timezone: "Asia/Ho_Chi_Minh",
    published_at: null,
    created_at: "2026-04-02T08:00:00Z",
  },
  {
    id: "s2",
    content_id: "ct3",
    platform_account_id: "pa2",
    scheduled_at: "2026-04-03T14:00:00Z",
    timezone: "Asia/Ho_Chi_Minh",
    published_at: null,
    created_at: "2026-04-02T08:00:00Z",
  },
  {
    id: "s3",
    content_id: "ct7",
    platform_account_id: "pa2",
    scheduled_at: "2026-04-01T11:00:00Z",
    timezone: "Asia/Ho_Chi_Minh",
    published_at: "2026-04-01T11:00:00Z",
    created_at: "2026-04-01T06:00:00Z",
  },
];

export const mockTemplates: ContentTemplate[] = [
  {
    id: "t1",
    name: "Hook \u2192 V\u1ea5n \u0111\u1ec1 \u2192 Gi\u1ea3i ph\u00e1p \u2192 CTA",
    description: "M\u1eabu b\u00e0i \u0111\u0103ng kinh \u0111i\u1ec3n cho qu\u1ea3ng c\u00e1o game",
    content_type: "social_post",
    platform: null,
    structure: {
      sections: [
        { name: "Hook", description: "C\u00e2u m\u1edf \u0111\u1ea7u g\u00e2y ch\u00fa \u00fd, t\u1ea1o t\u00f2 m\u00f2", char_limit: 50 },
        { name: "V\u1ea5n \u0111\u1ec1 / T\u00ecnh hu\u1ed1ng", description: "N\u00eau v\u1ea5n \u0111\u1ec1 ho\u1eb7c t\u00ecnh hu\u1ed1ng game th\u1ee7 g\u1eb7p ph\u1ea3i" },
        { name: "Gi\u1ea3i ph\u00e1p / \u0110i\u1ec3m nh\u1ea5n", description: "Gi\u1edbi thi\u1ec7u t\u00ednh n\u0103ng game gi\u1ea3i quy\u1ebft v\u1ea5n \u0111\u1ec1" },
        { name: "CTA", description: "K\u00eau g\u1ecdi h\u00e0nh \u0111\u1ed9ng: t\u1ea3i game, tham gia event...", char_limit: 30 },
      ],
    },
    example_output: "\u2694\ufe0f B\u1ea1n \u0111\u00e3 s\u1eb5n s\u00e0ng cho tr\u1eadn chi\u1ebfn l\u1edbn nh\u1ea5t?\n\nH\u00e0ng ng\u00e0n game th\u1ee7 \u0111ang loay hoay t\u00ecm guild m\u1ea1nh \u0111\u1ec3 raid boss...\n\nSeason 5 mang \u0111\u1ebfn h\u1ec7 th\u1ed1ng guild ho\u00e0n to\u00e0n m\u1edbi - t\u00ecm \u0111\u1ed3ng \u0111\u1ed9i, chia s\u1ebb chi\u1ebfn l\u1ee3i ph\u1ea9m!\n\n\ud83d\udc49 T\u1ea3i ngay v\u00e0 tham gia tr\u1eadn raid \u0111\u1ea7u ti\u00ean!",
    is_active: true,
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "t2",
    name: "TikTok Trend Hook",
    description: "M\u1eabu cho video TikTok ng\u1eafn, b\u1eaft trend",
    content_type: "social_post",
    platform: "tiktok",
    structure: {
      sections: [
        { name: "Hook (3 gi\u00e2y \u0111\u1ea7u)", description: "C\u00e2u g\u00e2y s\u1ed1c ho\u1eb7c trend \u0111ang hot, ph\u1ea3i gi\u1eef ch\u00e2n viewer", char_limit: 40 },
        { name: "N\u1ed9i dung ch\u00ednh", description: "Showcase gameplay ho\u1eb7c t\u00ednh n\u0103ng, nhanh g\u1ecdn" },
        { name: "Plot twist / Reveal", description: "B\u1ea5t ng\u1edd cu\u1ed1i video \u0111\u1ec3 t\u0103ng replay" },
        { name: "CTA ng\u1eafn", description: "Link in bio, t\u1ea3i ngay", char_limit: 20 },
      ],
    },
    example_output: null,
    is_active: true,
    created_at: "2026-03-22T14:00:00Z",
    updated_at: "2026-03-22T14:00:00Z",
  },
  {
    id: "t3",
    name: "Video Ad 30s",
    description: "K\u1ecbch b\u1ea3n qu\u1ea3ng c\u00e1o video 30 gi\u00e2y chu\u1ea9n",
    content_type: "video_script",
    platform: null,
    structure: {
      sections: [
        { name: "Hook (0-3s)", description: "H\u00ecnh \u1ea3nh/\u00e2m thanh g\u00e2y ch\u00fa \u00fd ngay l\u1eadp t\u1ee9c" },
        { name: "Problem (3-8s)", description: "N\u00eau pain point c\u1ee7a game th\u1ee7" },
        { name: "Solution (8-20s)", description: "Showcase gameplay, t\u00ednh n\u0103ng gi\u1ea3i quy\u1ebft pain point" },
        { name: "Social Proof (20-25s)", description: "S\u1ed1 li\u1ec7u, review, c\u1ed9ng \u0111\u1ed3ng" },
        { name: "CTA (25-30s)", description: "Logo, n\u00fat t\u1ea3i, \u01b0u \u0111\u00e3i n\u1ebfu c\u00f3" },
      ],
    },
    example_output: null,
    is_active: true,
    created_at: "2026-03-25T09:00:00Z",
    updated_at: "2026-03-25T09:00:00Z",
  },
];

// Dashboard stats
export const mockStats = {
  totalContent: mockContent.length,
  pendingReview: mockContent.filter((c) => c.status === "pending_review").length,
  published: mockContent.filter((c) => c.status === "published").length,
  scheduled: mockContent.filter((c) => c.status === "scheduled").length,
  activeCampaigns: mockCampaigns.filter((c) => c.status === "active").length,
  totalBrands: mockBrands.length,
  platformAccounts: mockPlatformAccounts.length,
  rejected: mockContent.filter((c) => c.status === "rejected").length,
};
